export const projects = [
	{project: "opensea", chain: "ethereum"},
	{project: "magic-eden", chain: "solana"},
	{project: "atomicmarket", chain: "wax"},
	{project: "decentraland", chain: "ethereum"},
	{project: "solanart", chain: "solana"},
	{project: "rarible", chain: "ethereum"},
	{project: "the-sandbox-marketplace", chain: "ethereum"},
	{project: "nftrade", chain: "avalanche"},
	{project: "nftrade", chain: "ethereum"},
	{project: "nftrade", chain: "binance-smart-chain"},
	{project: "nftrade", chain: "polygon"},
	{project: "superrare-co", chain: "ethereum"},
	{project: "foundation", chain: "ethereum"},
	{project: "solsea", chain: "solana"},
	{project: "hic-et-nunc", chain: "tezos"},
	{project: "treasureland", chain: "ethereum"},
	{project: "treasureland", chain: "binance-smart-chain"},
	{project: "treasureland", chain: "polygon"},
	{project: "mochi-market", chain: "binance-smart-chain"},
	{project: "playdapp-marketplace", chain: "polygon"},
	{project: "objkt-com", chain: "tezos"},
	{project: "digitaleyes-market", chain: "solana"},
	{project: "airnfts", chain: "binance-smart-chain"},
	{project: "altura-nft-marketplace", chain: "binance-smart-chain"},
	{project: "kalamint", chain: "tezos"},
];